### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [chachochach/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the page looks good. You used some good techniques here and kept your code well organized. Take a look at the issues I created as they will help you tweak some things for better efficiency and organization. Project will be increasing greatly in size and complexity from here on out so this will be important to optimize. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by chachochach** [comment]
Thanks Ryan! I like the points you brought to my attention..they were very objective and practical. I have applied them on the current project and will keep them in mind on future projects as your organizational tips were very useful. Thank you.
